### ISSUE TITLE
Downstream unknown unicast and broadcast in N:1

### ISSUE THREAD

**Issue by wdl2015** [balapi/netconf-polt#14]
Hi experts, 

From the code in xpon_apply_n_1_flow_create() -> xpon_create_bal_group_member() downstream unicast GEM ports are added in the group object. Does this mean the downstream unknown unicast and broadcast traffics will be for flooded to these GEM ports. This is different from TR-156 R110 and R112, which ask unknown unicast and broadcast traffics are flooded to downstream incidental broadcast GEM ports.

My question is whether netconf-polt has any plan to make N:1 downstream UC and BC TR-156 compliant.

5.4.3 Unknown MAC address frames at the OLT
R-109 It MUST be possible to configure each N:1 VLAN so that the OLT either silently discards or floods frames with MAC addresses that are not in the AN forwarding table.
R-110 For N:1 VLANs where flooding is enabled, when the OLT receives a tagged frame with an unknown unicast MAC address then **it MUST be forwarded to the incidental broadcast GEM port.**
Note: Use of the incidental broadcast GEM port implies that the ONUs on the PON are provisioned to allow receiving traffic from this GEM port.
5.4.4 Broadcast MAC address frames at the OLT
There are many filtering options that allow avoiding broadcast Ethernet frames for consumer access VLANs, however it is possible to turn these features off, so that broadcast is possible in N:1 VLANs.
R-111 It MUST be possible to configure each VLAN so that it silently discards broadcast frames.
R-112 For N:1 VLANs, when the OLT receives a broadcast frame, and if it is not otherwise filtered, then **it MUST be forwarded to the incidental broadcast GEM port.**

Thank you.

Br
George Deng

**Comment by igortern** [comment]
Hi George,
The 1st step in making netconf-polt N:1 implementation TR-156 compliant is to implement N:1 :). Currently only 1:1 is supported. There is some initial N:1 code, but it is preliminary and doesn't work. In the moment there is no schedule for N:1 implementation.
Regards,
Igor

**Comment by wdl2015** [comment]
Hi Igor, 
Thanks for this information. 
Br
George Deng
